name: cdn

environment:
  sdk: ">=2.17.0 <3.0.0"

dev_dependencies:
  build_runner: any
  build_web_compilers: any

dependencies:
  crypto: ^3.0.1
  http: ^1.1.2
  intl: ^0.19.0
  js: ^0.6.4
  yaml: ^3.1.1
